package com.yzw.otherdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yzw.OtherInfo;

import com.yzw.otherdao.OtherInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class OtherDaoSession extends AbstractDaoSession {

    private final DaoConfig otherInfoDaoConfig;

    private final OtherInfoDao otherInfoDao;

    public OtherDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        otherInfoDaoConfig = daoConfigMap.get(OtherInfoDao.class).clone();
        otherInfoDaoConfig.initIdentityScope(type);

        otherInfoDao = new OtherInfoDao(otherInfoDaoConfig, this);

        registerDao(OtherInfo.class, otherInfoDao);
    }
    
    public void clear() {
        otherInfoDaoConfig.getIdentityScope().clear();
    }

    public OtherInfoDao getOtherInfoDao() {
        return otherInfoDao;
    }

}
