package com.yzw.dazzdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yzw.Album;
import com.yzw.Person;
import com.yzw.PersonInfo;
import com.yzw.Song;

import com.yzw.dazzdao.AlbumDao;
import com.yzw.dazzdao.PersonDao;
import com.yzw.dazzdao.PersonInfoDao;
import com.yzw.dazzdao.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DazzDaoSession extends AbstractDaoSession {

    private final DaoConfig albumDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig personInfoDaoConfig;
    private final DaoConfig songDaoConfig;

    private final AlbumDao albumDao;
    private final PersonDao personDao;
    private final PersonInfoDao personInfoDao;
    private final SongDao songDao;

    public DazzDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumDaoConfig = daoConfigMap.get(AlbumDao.class).clone();
        albumDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        albumDao = new AlbumDao(albumDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(Album.class, albumDao);
        registerDao(Person.class, personDao);
        registerDao(PersonInfo.class, personInfoDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        albumDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        personInfoDaoConfig.getIdentityScope().clear();
        songDaoConfig.getIdentityScope().clear();
    }

    public AlbumDao getAlbumDao() {
        return albumDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
